pocMoneyField/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pocapp.urls')),

    path('admin/', admin.site.urls),
]

"""
Premier probleme ;
Espace ou point : a l'enregistrement pas un nombre
Imput en type text puis bdd : fonctionne avec thousand sep de django (meme sur les années)

"""

pocapp/urls.py
from django.urls import path

from pocapp.views import VueExemple

app_name = 'pocapp'
urlpatterns = [
    path('exemple/', VueExemple.as_view(), name='exemple'),
]

pocapp/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models


class MaClasseAvecDesNombres(models.Model):
    nombre1 = models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('0.00'))])
    nombre2 = models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('0.00'))])

pocapp/forms.py
from django import forms

from django.forms import widgets


from pocapp.models import MaClasseAvecDesNombres


class FormMaClasseAvecDesNombres(forms.ModelForm):
    class Meta:
        model = MaClasseAvecDesNombres
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(FormMaClasseAvecDesNombres, self).__init__(*args, **kwargs)

        self.fields['nombre1'].widget = widgets.TextInput()
        self.fields['nombre2'].widget = widgets.TextInput()

        # Gestion des champs nombre
        champs_texte_decimal = ['nombre1', 'nombre2']
        champs_readonly = ['nombre2']

        # Ajout des classes + champs obligatoire.
        for (nom, champ) in self.fields.items():
            if nom in champs_texte_decimal:
                self.fields[nom].widget.attrs['class'] = 'form-control decimal2'

            if nom in champs_readonly:
                self.fields[nom].widget.attrs['readonly'] = True

pocapp/views.py
from django.views.generic import TemplateView

from pocapp.forms import FormMaClasseAvecDesNombres
from pocapp.models import MaClasseAvecDesNombres


class VueExemple(TemplateView):
    template_name = 'pocapp/exemple.html'

    def get_context_data(self, form=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mes_nombres'] = MaClasseAvecDesNombres.objects.all()
        context['form'] = form if form else FormMaClasseAvecDesNombres()
        return context

    def post(self, request, **kwargs):
        form = FormMaClasseAvecDesNombres(request.POST)
        context = self.get_context_data(form=form, **kwargs)

        if not form.is_valid():
            return self.render_to_response(context, status=400)

        form.save()

        return self.render_to_response(context, status=201)

templates/pocapp/exemple.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Top navbar example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
<main role="main" class="container">
    <div class="jumbotron">
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Créer</button>
        </form>

        <ul>
            {% for nombre in mes_nombres %}
                <li>Nombre #{{ nombre.id }} --> nombre1 : {{ nombre.nombre1 }} € - nombre2 : {{ nombre.nombre2 }} €
                </li>
            {% endfor %}
        </ul>
    </div>
</main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/autonumeric"></script>

<script>
    function initialisationDesChampsAutoNumeric() {
        $('.decimal2').each(function () {
            let readOnly = false;
            if ($(this).is('[readonly]')) {
                readOnly = true;
            }
            new AutoNumeric('#' + $(this).attr('id'), {
                aSep: ' ',
                aDec: '.',
                vMin: '0.00',
                currencySymbol : ' €',
                readOnly: readOnly,
            }).french();
        });
    }

    $('#id_nombre1').on('change', function () {
        AutoNumeric.getAutoNumericElement($('#id_nombre2').get(0)).set(AutoNumeric.getNumber('#' + $(this).attr('id')) * 2)
    });

    $('form').on('submit', function (e) {
        $(this).find('.decimal2').each(function () {
            $(this).val(AutoNumeric.getNumber('#' + $(this).attr('id')));
        });
    });

    $(document).ready(function () {
        initialisationDesChampsAutoNumeric();
    });

</script>
</body>
</html>